name: Trigger auto deployment for container-app-kpjr6dh4s6gs4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-kpjr6dh4s6gs4-AutoDeployTrigger-958a66f6-1ee6-4ed8-b737-90db237b8c8e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPKPJR6DH4S6GS4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPKPJR6DH4S6GS4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPKPJR6DH4S6GS4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPKPJR6DH4S6GS4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPKPJR6DH4S6GS4_REGISTRY_PASSWORD }}
          containerAppName: container-app-kpjr6dh4s6gs4
          resourceGroup: appspacesragappaccfbde6
          imageToBuild: default/container-app-kpjr6dh4s6gs4:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


